### ISSUE TITLE
No wifi after removing flash

### ISSUE THREAD

**Issue by gallegonovato** [CHEF-KOCH/Flash_remover#1]
Good afternoon:

I tried to remove flash from my windows 10 home. I did it with the official adobe tool. It's even all good. I restarted when you asked me to. But then I find that the wifi puts me online or secure. But it doesn't work.

Instead with cell phones, tablets or other equipment the wifi works.

I restarted the computer and it was still connected and next to it there was another word that I don't remember now.

If I restore the computer to the restore point that I created before uninstalling everything returns to normal.

With the files that you have in this subject you have to do it with Powershell?. Or how is it done?.

Could you guide me through it because I'm out of wifi?.

Or help me remove the adobe flash?.

A hug and thanks for your time, help and patience.

**Comment by CHEF-KOCH** [comment]
Never heard more bullshit.
